name: Build and deploy .NET Core application
on:
  push:
    branches:
      - main

      
env:
  AZURE_WEBAPP_NAME: levanhiep409159
  AZURE_WEBAPP_PACKAGE_PATH: App.Frontend\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: ./src/App.Frontend

  
jobs:
  build:
    environment: production
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}

        
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore Dependencies
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp-dotnet-version-${{ env.DOTNET_CORE_VERSION }}
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

        
  deploy:
    runs-on: ubuntu-latest
    needs: build

    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp-dotnet-version-${{ env.DOTNET_CORE_VERSION }}
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.LEVANHIEP409159_8286 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
